name: Automated release
on:
  push:
    branches:
      - main
  release:
    types:
      - created
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Generate macOS app
    runs-on: macos-latest
    permissions:
      contents: write
      packages: write
      actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 16
      - run: npm install --global create-dmg
      - uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          p12-password: ${{ secrets.P12_PASSWORD }}
      # Only bump version for release events
      - name: Bump version
        if: github.event_name == 'release'
        uses: sirily11/ios-bump-version@master
        with:
          version: ${{ github.ref_name }}
          build-number: ${{github.run_attempt }}
      - name: Build
        run: |
          gem install xcpretty
          set -o pipefail && xcodebuild -destination platform=macOS \
            -scheme trading-analyzer \
            -configuration Release \
            -archivePath output/output.xcarchive \
            -allowProvisioningUpdates \
            CODE_SIGN_IDENTITY="${{ secrets.SIGNING_CERTIFICATE_NAME }}" \
            CODE_SIGN_STYLE=Manual \
            OTHER_CODE_SIGN_FLAGS="--options=runtime --timestamp" \
            archive | xcpretty
      - name: Notarize
        run: ./scripts/notary.sh
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PWD: ${{ secrets.APPLE_ID_PWD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

      # Upload artifact for Pull Requests (1 day retention)
      - name: Upload artifact for PR
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: TradingAnalyzer-PR-${{ github.event.pull_request.number }}
          path: TradingAnalyzer.dmg
          retention-days: 1

      # Upload to release for release events
      - name: Upload DMG to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: TradingAnalyzer.dmg
          token: ${{ secrets.GITHUB_TOKEN }}
